# DataSource

ds.database-driver=com.mysql.jdbc.Driver
ds.url=jdbc:mysql://gat-serverpc:3306/csharp?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
ds.username=csharp
ds.password=csharp
