# DataSource

ds.database-driver=com.mysql.cj.jdbc.Driver
ds.url=jdbc:mysql://localhost:3306/csharp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull
ds.username=root
ds.password=csharp

#参考資料（3データベースの設定方法）
#・localhost:3306→ここでは接続先を設定します、自分のｐｃであればlocalhostと記載します、外部のサーバの場合には、gat-serverpc3:3306とサーバー名を変更します。
#・ds.username=root ds.password=root ここではサーバーをインストールした際につけたrootユーザのパスワードを入れます。
#・csharp→ここにはDBの名前を記載します、スキームとも言います。
